openapi: 3.0.0
info:
  description: 'Ocr-server-api'
  version: "1.0.0"
  title: 'OCR SERVER API'
tags:
  - name: ocr-runtime
    
paths:
  /api/v1/ocr/process:
    post:
      tags: 
        - ocr-runtime
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OcrRequestDto"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcrResponseDto"

components:
  schemas:
    OcrRequestDto:
      type: object
      properties:
        ImageId: 
          type: string
        Image:
          $ref: "#/components/schemas/ImageDto"

    OcrResponseItem:
      type: object
      properties:
        ProcessorKey:
          type: string
        Text:
          type: string

    OcrResponseDto:
      type: object
      properties:
        ImageThumb:
          $ref: "#/components/schemas/ThumbnailDto"
        Image:
          $ref: "#/components/schemas/ImageDto"
        Embedding:
          $ref: "#/components/schemas/EmbeddingDto"
        ImageText:
          type: array
          items:
            $ref: "#/components/schemas/OcrResponseItem"

    EmbeddingDto:
      type: object
      properties:
        data: 
          type: array
          items:
            type: number
        ModelName:
          type: string
        
    ThumbnailDto:
      type: object
      properties:
        Image:
            $ref: "#/components/schemas/ImageDto"
        Width:
          type: integer
        Height:
          type: integer

    ImageDto:
      type: object
      properties:
        MimeType:
          type: string
        ImageBase64:
          type: string
