FROM golang:1.25.0-alpine AS builder

WORKDIR /app
RUN apk add --update --no-cache bash curl \
    gcc g++ vips vips-dev vips-poppler pkgconf \
    poppler-dev musl-dev libc6-compat 

COPY ./services/gen gen/
COPY ./services/common common/

COPY ./services/telegram-service ./telegram-service

WORKDIR /app/telegram-service
RUN go build -a -installsuffix cgo -o output.bin

FROM alpine:latest 

WORKDIR /app
RUN apk add curl
COPY --from=builder /app/telegram-service/output.bin telegram-service

WORKDIR /app/config
ENV APPLICATION_CONFIGPATH "/app/config"

WORKDIR /app
ENTRYPOINT [ "/app/telegram-service" ]