{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-config
  labels:
    {{- include "memelo.serviceLabels" (dict "root" $ "name" $name) | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{- include (printf "memelo.config.%s" $name) $ | nindent 4 }}
---
{{- end }}
