server:
  ListenAddress: :7001

image-storage:
  S3:
    Endpoint: localhost:9000
    AccessKey: minio123
    SecretKey: minio123
    Bucket: images


ocr:
  Url: http://localhost:7002

metadata-storage:
  Elastic:
    Addresses:
      - "http://localhost:9200/"
    Username: elastic
    Password: elastic
  Index: image-metadata