server:
  ListenAddress: :7001

image-storage:
  S3:
    Endpoint: localhost:9000
    AccessKey: 
    SecretKey: 
    Bucket: images


ocr-service:
  Uri: http://localhost:7002

metadata-storage:
  Elastic:
    Addresses:
      - "http://localhost:9200/"
    Username: 
    Password: 
  Index: image-metadata
  EmbeddingV1Dimensions: 1408
  EmbeddingMatchTreshold: 0.955