server:
  ListenAddress: :7001

image-storage:
  S3:
    Endpoint: eropus.ru
    AccessKey: minio123
    SecretKey: 9f97d6bcfe2d2130
    Bucket: images


ocr-service:
  Uri: http://localhost:7002

metadata-storage:
  Elastic:
    Addresses:
      - "http://localhost:9200/"
    Username: elastic
    Password: elastic
  Index: image-metadata