openapi: 3.0.0
info:
  description: ''
  version: "1.0.0"
  title: 'Meme-server'
tags:
  - name: meme-crud
    
paths:
  /api/v1/meme:
    post:
      tags: 
        - meme-crud
      operationId: "CreateMeme"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageDto"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MemeDto"

  /api/v1/meme/{MemeId}:
    get:
      parameters:
        - $ref: "#/components/parameters/MemeId"
      tags: 
        - meme-crud
      operationId: "GetMemeInfo"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MemeDto"

  /api/v1/meme/{MemeId}/image:
    get:
      parameters:
        - $ref: "#/components/parameters/MemeId"
      tags: 
        - meme-crud
      operationId: "GetMemeImage"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageDto"



components: 
  parameters:
    MemeId:
      in: path
      required: true
      name: MemeId
      schema:
        type: string

  schemas:
    ImageDto:
      type: object
      properties:
        Filename:
          type: string
        Data: 
          type: string
    
    MemeDto:
      type: object
      properties:
        Id:
          type: string
        OcrResult:
          type: array
          items: 
            type: string
        Hash:
          type: string
        
